# Generated by Django 3.2 on 2022-02-07 14:48

from django.conf import settings
import django.contrib.postgres.fields
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant_bot', '0003_alter_addressbook_email_alter_addressbook_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetListFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='addressbook',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\+?(38)?0(44|67|68|96|97|98|50|66|95|99|63|73|93|89|94)\\d{7}$', 'Enter correct number')]),
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
